// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr9ltXcePNsSfHzoxlXC-IDWt9D3i0ao0',
    appId: '1:1088784812118:web:1acbbd8130620876cb93f7',
    messagingSenderId: '1088784812118',
    projectId: 'week8-9-339e0',
    authDomain: 'week8-9-339e0.firebaseapp.com',
    storageBucket: 'week8-9-339e0.firebasestorage.app',
    measurementId: 'G-S9PJJ45SE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClUHnN1rjNAV_yZoHlLHepFYFDxUkQAwo',
    appId: '1:1088784812118:android:066c0ed184e2c281cb93f7',
    messagingSenderId: '1088784812118',
    projectId: 'week8-9-339e0',
    storageBucket: 'week8-9-339e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2gQ9b4AmmyyUp3FLp9O_fpFIQA7Lht40',
    appId: '1:1088784812118:ios:e8fd23992df829e9cb93f7',
    messagingSenderId: '1088784812118',
    projectId: 'week8-9-339e0',
    storageBucket: 'week8-9-339e0.firebasestorage.app',
    iosBundleId: 'com.example.week8Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2gQ9b4AmmyyUp3FLp9O_fpFIQA7Lht40',
    appId: '1:1088784812118:ios:e8fd23992df829e9cb93f7',
    messagingSenderId: '1088784812118',
    projectId: 'week8-9-339e0',
    storageBucket: 'week8-9-339e0.firebasestorage.app',
    iosBundleId: 'com.example.week8Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr9ltXcePNsSfHzoxlXC-IDWt9D3i0ao0',
    appId: '1:1088784812118:web:04068fc639259392cb93f7',
    messagingSenderId: '1088784812118',
    projectId: 'week8-9-339e0',
    authDomain: 'week8-9-339e0.firebaseapp.com',
    storageBucket: 'week8-9-339e0.firebasestorage.app',
    measurementId: 'G-615WVYLTX5',
  );
}
