// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUM-vi02hzCtla_SujKxhzrC0EiQeUF8c',
    appId: '1:102475672891:web:49f94726243d340d8d1b1e',
    messagingSenderId: '102475672891',
    projectId: 'week5-project-525c5',
    authDomain: 'week5-project-525c5.firebaseapp.com',
    storageBucket: 'week5-project-525c5.firebasestorage.app',
    measurementId: 'G-1HQSH7SNZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgRJC-1THCbiOsaSzRQLMFYNRRRKb-qls',
    appId: '1:102475672891:android:64ef399a8a0a81ea8d1b1e',
    messagingSenderId: '102475672891',
    projectId: 'week5-project-525c5',
    storageBucket: 'week5-project-525c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQImM1k88ogjmOJqNTlGsxA8f4QoGV-U0',
    appId: '1:102475672891:ios:17a95f1c9cd5ec6f8d1b1e',
    messagingSenderId: '102475672891',
    projectId: 'week5-project-525c5',
    storageBucket: 'week5-project-525c5.firebasestorage.app',
    iosBundleId: 'com.example.week5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQImM1k88ogjmOJqNTlGsxA8f4QoGV-U0',
    appId: '1:102475672891:ios:17a95f1c9cd5ec6f8d1b1e',
    messagingSenderId: '102475672891',
    projectId: 'week5-project-525c5',
    storageBucket: 'week5-project-525c5.firebasestorage.app',
    iosBundleId: 'com.example.week5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUM-vi02hzCtla_SujKxhzrC0EiQeUF8c',
    appId: '1:102475672891:web:c1c216d30f2fd9f28d1b1e',
    messagingSenderId: '102475672891',
    projectId: 'week5-project-525c5',
    authDomain: 'week5-project-525c5.firebaseapp.com',
    storageBucket: 'week5-project-525c5.firebasestorage.app',
    measurementId: 'G-LFG72N7C63',
  );
}
